data<-read.table("C:/Users/ayoub/Downloads/exdata_data_household_power_consumption/household_power_consumption.txt", sep = ";", header = TRUE)
data<- data %>% mutate(Date= as.Date(Date, format="%d/%m/%Y"))
data <- data %>% mutate(DateTime = strptime(paste(Date, Time), format = "%Y-%m-%d %H:%M:%S"))
data<- data %>% filter(Date=="2007-02-01" | Date=="2007-02-02")
data<- data %>% mutate(Global_active_power= as.numeric(Global_active_power))
plot(data$DateTime, data$Sub_metering_1, type='l', xlab = "", ylab = "Energy sub metering", col="Black")
lines(data$DateTime, data$Sub_metering_2, col="Red")
lines(data$DateTime, data$Sub_metering_3, col="Blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=1)
dev.copy(png, "plot3.png", width=408, height=408)
dev.off()